<?php

namespace common\models\measure;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use common\models\Test;
use Yii;

/**
 * This is the model class for table "courts_name".
 *
 * @property int $id
 * @property string $name
 * @property int $created_by
 * @property int $updated_by
 * @property int $created_at
 * @property int $updated_at
 *
 * @property CourtDecision[] $courtDecisions
 * @property User $createdBy
 * @property User $updatedBy
 */
class CourtsName extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'courts_name';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name',], 'required'],
            [['name'], 'string', 'max' => 255],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }
 

    // /**
    //  * {@inheritdoc}
    //  */
    public function attributeLabels()
    {
        return [
            'name' => 'Sud nomi',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Yaratilgan sanasi',
            'updated_at' => 'O\'zgartirilgan sanasi',
        ];
    }
    public function behaviors()
    {
        return [
            TimestampBehavior::class,
            BlameableBehavior::class,
        ];
    }
   
    public function afterFind()
    {
       
        $this->updated_at = Yii::$app->formatter->asDate($this->updated_at, 'dd.MM.yyyy');
        $this->created_at = Yii::$app->formatter->asDate($this->created_at, 'dd.MM.yyyy');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
    /**
     * Gets query for [[CourtDecisions]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCourtDecisions()
    {
        return $this->hasMany(CourtDecision::class, ['court_id' => 'id']);
    }

    /**
     * Gets query for [[CreatedBy]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
     * Gets query for [[UpdatedBy]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }
}
